# Generated by Django 2.0.2 on 2020-08-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(default='l', max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('month_s', models.CharField(default='J', max_length=100)),
                ('month_2', models.CharField(default='D', max_length=100)),
            ],
        ),
    ]
