# Generated by Django 2.0.2 on 2020-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='year1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='year2',
            field=models.IntegerField(default=2),
        ),
    ]
