# Generated by Django 2.0.2 on 2020-08-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_edu_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='college',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
